#!/usr/bin/env python3
"""YDK unified guard hook - all guard checks in one script."""

import json
import sys
from pathlib import Path

# Read stdin (Claude Code pipes tool context as JSON).
# select.select() on stdin is socket-only on Windows (raises WinError 10093
# for pipes/console handles) -- a plain blocking read is portable and safe
# here since the harness always closes stdin after writing the payload.
try:
    raw = sys.stdin.read()
except Exception:
    sys.exit(0)  # Unreadable stdin = allow

if not raw:
    sys.exit(0)  # No data = allow

try:
    data = json.loads(raw)
except (json.JSONDecodeError, ValueError):
    sys.exit(0)  # Bad data = fail open

tool_name = data.get("tool_name", "")
tool_input = data.get("tool_input", {})
cwd = data.get("cwd", ".")
file_path = tool_input.get("file_path", "")
command = tool_input.get("command", "")

# Normalize file_path (remove cwd prefix)
if file_path.startswith(cwd):
    file_path = file_path[len(cwd) :].lstrip("/")

root = Path(cwd)

# --- GUARD: no-manual-pr and no-direct-push ---
if tool_name == "Bash" and ("gh pr create" in command or "gh pr merge" in command):
    sys.stderr.write(
        "BLOCKED: Use 'ydk task done' to create PRs -- it captures verification proof.\n"
    )
    sys.exit(2)
# git push is allowed -- ydk task done needs it internally
# Only gh pr create is blocked (forces proof-based PRs)

# --- GUARD: no-proof-tamper ---
if (
    tool_name in ("Edit", "Write")
    and ".ydk/proofs/" in file_path
    and "summary.md" not in file_path
):
    sys.stderr.write(
        "BLOCKED: Proof files are generated by 'ydk task done'. Do not edit manually.\n"
    )
    sys.exit(2)

# --- GUARD: no-noqa ---
if tool_name in ("Edit", "Write"):
    new_content = tool_input.get("new_string", "") or tool_input.get("content", "")
    if new_content and not file_path.startswith("tests/"):
        for marker in ("# noqa", "# type: ignore", "# nosec"):
            if marker in new_content:
                sys.stderr.write(
                    f"BLOCKED: '{marker}' not allowed. Fix the violation instead of suppressing it.\n"
                )
                sys.exit(2)

# --- GUARD: no-mock-internals ---
if tool_name in ("Edit", "Write") and file_path.startswith("tests/"):
    new_content = tool_input.get("new_string", "") or tool_input.get("content", "")
    if new_content:
        for pattern in ('@patch("app.', '@patch("src.', "@patch('app.", "@patch('src."):
            if pattern in new_content:
                sys.stderr.write(
                    "BLOCKED: Don't mock internal classes. Use fakes and DI overrides.\n"
                )
                sys.exit(2)

# --- GUARD: stage-gate ---
state_file = root / ".ydk" / "state.json"
if state_file.exists() and file_path:
    try:
        state = json.loads(state_file.read_text())
        stage = state.get("stage", "00")

        # Stage 01/02: block source file edits
        if stage in ("01", "02") and file_path.startswith(("src/", "app/", "tests/")):
            if not file_path.startswith(".ydk/"):
                sys.stderr.write(
                    f"BLOCKED: Stage {stage} -- cannot edit source files yet.\n"
                )
                sys.exit(2)
    except Exception:
        pass  # State unreadable = allow

sys.exit(0)  # All checks passed -- allow
