using ExtractorOLE.DTOs;
using ExtractorOLE.Helpers;
using Microsoft.Extensions.DependencyInjection;
using SampleGenerator.Abstractions;
using SampleGenerator.Fixtures;
using SampleGenerator.Generators;
using Xunit;

namespace ExtractorOLE.Tests.SampleGeneration
{
    // T-b856b14e: DocSampleGenerator authors a real legacy .doc (docs/adrs/005-legacy-doc-ppt-authoring.md).
    // Every test reads the generated bytes back through ExtractorOLE's public Extract path
    // (DocOpenStrategy + the b2xtranslator-backed DocTextExtractor), never through the generator.
    public class DocSampleGeneratorTests
    {
        private static readonly string[] Lines =
        {
            MultilingualFixtures.Hebrew,
            MultilingualFixtures.Arabic,
            MultilingualFixtures.Persian,
            MultilingualFixtures.Russian,
            MultilingualFixtures.Latin,
            MultilingualFixtures.Cjk,
            MultilingualFixtures.EmojiSimple,
            MultilingualFixtures.EmojiFamilyZwj,
            MultilingualFixtures.EmojiSkinTone,
            MultilingualFixtures.EmojiFlagZwj,
            "café café", // decomposed + precomposed: any Unicode normalization would collapse these
        };

        internal static DocumentExtractionResult Extract(byte[] bytes, OfficeMimeTypeEnum format)
        {
            var services = new ServiceCollection();
            ServiceRegistration.Register(services);
            var provider = services.BuildServiceProvider();
            var helper = provider.GetRequiredService<IExtractionHelper>();

            return provider.GetRequiredService<MainExtractor>().Extract(new ExtractionRequest
            {
                FileBytes = bytes,
                FileName = "sample",
                DetectedMimeType = helper.MimeFor(format),
            });
        }

        [Fact]
        public void Generate_DoesNotThrowAndProducesCfbDetectedAsWordLegacy()
        {
            var sample = new DocSampleGenerator().Generate(new SampleSpec { BodyText = "hello" });

            Assert.Equal("sample.doc", sample.FileName);
            Assert.Equal(OfficeMimeTypeEnum.WordLegacy,
                new ExtractionHelper().DetectMimeTypeFromBytes(sample.Content));
        }

        [Fact]
        public void RoundTrip_MultilingualAndEmojiBody_ReadsBackExactly()
        {
            var sample = new DocSampleGenerator().Generate(new SampleSpec
            {
                BodyText = string.Join(Environment.NewLine, Lines),
            });

            var result = Extract(sample.Content, OfficeMimeTypeEnum.WordLegacy);

            Assert.Equal(string.Join(Environment.NewLine, Lines), result.ExtractedText);
        }

        [Theory]
        [InlineData(0, "Hebrew")]
        [InlineData(1, "Arabic")]
        [InlineData(2, "Persian")]
        [InlineData(3, "Russian")]
        [InlineData(4, "Latin")]
        [InlineData(5, "Cjk")]
        [InlineData(6, "emoji simple")]
        [InlineData(7, "emoji ZWJ family")]
        [InlineData(8, "emoji skin tone")]
        [InlineData(9, "emoji ZWJ flag")]
        [InlineData(10, "combining sequence, not normalized")]
        public void RoundTrip_EachFixtureRoundTripsWithExactStringEquality(int index, string label)
        {
            var sample = new DocSampleGenerator().Generate(new SampleSpec { BodyText = Lines[index] });

            var result = Extract(sample.Content, OfficeMimeTypeEnum.WordLegacy);

            Assert.True(Lines[index] == result.ExtractedText, $"{label}: expected '{Lines[index]}', got '{result.ExtractedText}'");
        }

        [Fact]
        public void RoundTrip_LargeMultiParagraphBody_SpansSeveralParagraphFkpPages()
        {
            var body = MultilingualFixtures.ComposeLargeBody(5_000, 20).Replace("\r\n", "\n");
            var sample = new DocSampleGenerator().Generate(new SampleSpec { BodyText = body });

            var result = Extract(sample.Content, OfficeMimeTypeEnum.WordLegacy);

            Assert.Equal(body.Replace("\n", Environment.NewLine), result.ExtractedText);
        }

        [Fact]
        public void RoundTrip_MetadataEmbeddingsAndMacros_ReadBackThroughDocOpenStrategy()
        {
            var sample = new DocSampleGenerator().Generate(new SampleSpec
            {
                BodyText = "body",
                Metadata = new Dictionary<string, string>
                {
                    [MetadataFields.Title] = MultilingualFixtures.Hebrew,
                    [MetadataFields.Author] = MultilingualFixtures.Arabic,
                    [MetadataFields.LastModifiedBy] = MultilingualFixtures.Cjk,
                    [MetadataFields.Created] = "2026-02-03T00:00:00Z",
                    [MetadataFields.Modified] = "2026-03-19T00:00:00Z",
                },
                Embeddings =
                {
                    new EmbeddedContentSpec { FileName = "a.bin", Content = new byte[] { 1, 2, 3 } },
                    new EmbeddedContentSpec { FileName = "b.bin", Content = new byte[] { 4, 5, 6, 7 } },
                },
                VbaProject = new byte[] { 0xAA, 0xBB },
            });

            var result = Extract(sample.Content, OfficeMimeTypeEnum.WordLegacy);

            Assert.Equal(MultilingualFixtures.Hebrew, result.Metadata.Title);
            Assert.Equal(MultilingualFixtures.Arabic, result.Metadata.Creator);
            Assert.Equal(MultilingualFixtures.Cjk, result.Metadata.LastModifiedBy);
            Assert.Equal(new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), result.Metadata.Created!.Value.ToUniversalTime());
            Assert.Equal(new DateTime(2026, 3, 19, 0, 0, 0, DateTimeKind.Utc), result.Metadata.Modified!.Value.ToUniversalTime());
            Assert.Equal(2, result.EmbeddedFiles.Count);
            Assert.True(((WordFormatMetadata)result.FormatMetadata!).HasMacros);
        }

        [Fact]
        public void RoundTrip_NoMacroSpec_HasMacrosFalse()
        {
            var sample = new DocSampleGenerator().Generate(new SampleSpec { BodyText = "body" });

            var result = Extract(sample.Content, OfficeMimeTypeEnum.WordLegacy);

            Assert.False(((WordFormatMetadata)result.FormatMetadata!).HasMacros);
        }

        [Fact]
        public void RoundTrip_EmptyBody_ProducesReadableFileWithEmptyText()
        {
            var sample = new DocSampleGenerator().Generate(new SampleSpec());

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.WordLegacy);

            Assert.Equal(string.Empty, result.ExtractedText);
        }
    }
}
