using ExtractorOLE.DTOs;
using ExtractorOLE.Helpers;
using SampleGenerator.Abstractions;
using SampleGenerator.Fixtures;
using SampleGenerator.Generators;
using Xunit;

namespace ExtractorOLE.Tests.SampleGeneration
{
    // T-b856b14e: PptSampleGenerator authors a real legacy .ppt (docs/adrs/005-legacy-doc-ppt-authoring.md).
    // Every test reads the generated bytes back through ExtractorOLE's public Extract path
    // (PptOpenStrategy + the b2xtranslator-backed PptTextExtractor), never through the generator.
    public class PptSampleGeneratorTests
    {
        private static readonly string[] Lines =
        {
            MultilingualFixtures.Hebrew,
            MultilingualFixtures.Arabic,
            MultilingualFixtures.Persian,
            MultilingualFixtures.Russian,
            MultilingualFixtures.Latin,
            MultilingualFixtures.Cjk,
            MultilingualFixtures.EmojiSimple,
            MultilingualFixtures.EmojiFamilyZwj,
            MultilingualFixtures.EmojiSkinTone,
            MultilingualFixtures.EmojiFlagZwj,
            "café café",
        };

        [Fact]
        public void Generate_DoesNotThrowAndProducesCfbDetectedAsPowerPointLegacy()
        {
            var sample = new PptSampleGenerator().Generate(new SampleSpec { BodyText = "hello" });

            Assert.Equal("sample.ppt", sample.FileName);
            Assert.Equal(OfficeMimeTypeEnum.PowerPointLegacy,
                new ExtractionHelper().DetectMimeTypeFromBytes(sample.Content));
        }

        [Fact]
        public void RoundTrip_MultilingualAndEmojiBody_ReadsBackExactly()
        {
            var sample = new PptSampleGenerator().Generate(new SampleSpec
            {
                BodyText = string.Join(Environment.NewLine, Lines),
            });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.PowerPointLegacy);

            Assert.Equal(string.Join(Environment.NewLine, Lines), result.ExtractedText);
            Assert.Equal(1, ((PowerPointFormatMetadata)result.FormatMetadata!).SlideCount);
        }

        [Theory]
        [InlineData(0, "Hebrew")]
        [InlineData(1, "Arabic")]
        [InlineData(2, "Persian")]
        [InlineData(3, "Russian")]
        [InlineData(4, "Latin")]
        [InlineData(5, "Cjk")]
        [InlineData(6, "emoji simple")]
        [InlineData(7, "emoji ZWJ family")]
        [InlineData(8, "emoji skin tone")]
        [InlineData(9, "emoji ZWJ flag")]
        [InlineData(10, "combining sequence, not normalized")]
        public void RoundTrip_EachFixtureRoundTripsWithExactStringEquality(int index, string label)
        {
            var sample = new PptSampleGenerator().Generate(new SampleSpec { BodyText = Lines[index] });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.PowerPointLegacy);

            Assert.True(Lines[index] == result.ExtractedText, $"{label}: expected '{Lines[index]}', got '{result.ExtractedText}'");
        }

        [Fact]
        public void RoundTrip_LargeMultiLineBody_ReadsBackExactly()
        {
            var body = MultilingualFixtures.ComposeLargeBody(5_000, 20).Replace("\r\n", "\n");
            var sample = new PptSampleGenerator().Generate(new SampleSpec { BodyText = body });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.PowerPointLegacy);

            Assert.Equal(body.Replace("\n", Environment.NewLine), result.ExtractedText);
        }

        [Fact]
        public void RoundTrip_MetadataEmbeddingsAndMacros_ReadBackThroughPptOpenStrategy()
        {
            var sample = new PptSampleGenerator().Generate(new SampleSpec
            {
                BodyText = "body",
                Metadata = new Dictionary<string, string>
                {
                    [MetadataFields.Title] = MultilingualFixtures.Hebrew,
                    [MetadataFields.Author] = MultilingualFixtures.Arabic,
                    [MetadataFields.LastModifiedBy] = MultilingualFixtures.Cjk,
                    [MetadataFields.Created] = "2026-02-03T00:00:00Z",
                    [MetadataFields.Modified] = "2026-03-19T00:00:00Z",
                },
                Embeddings =
                {
                    new EmbeddedContentSpec { FileName = "a.bin", Content = new byte[] { 1, 2, 3 } },
                    new EmbeddedContentSpec { FileName = "b.bin", Content = new byte[] { 4, 5, 6, 7 } },
                },
                VbaProject = new byte[] { 0xAA, 0xBB },
            });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.PowerPointLegacy);

            Assert.Equal(MultilingualFixtures.Hebrew, result.Metadata.Title);
            Assert.Equal(MultilingualFixtures.Arabic, result.Metadata.Creator);
            Assert.Equal(MultilingualFixtures.Cjk, result.Metadata.LastModifiedBy);
            Assert.Equal(new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), result.Metadata.Created!.Value.ToUniversalTime());
            Assert.Equal(new DateTime(2026, 3, 19, 0, 0, 0, DateTimeKind.Utc), result.Metadata.Modified!.Value.ToUniversalTime());
            // PptOpenStrategy reports every top-level storage as an embedded object, so the
            // "Macros" storage is counted alongside the two embeddings.
            Assert.Equal(3, result.EmbeddedFiles.Count);
            Assert.True(((PowerPointFormatMetadata)result.FormatMetadata!).HasMacros);
        }

        [Fact]
        public void RoundTrip_NoMacroSpec_HasMacrosFalseAndNoEmbeddings()
        {
            var sample = new PptSampleGenerator().Generate(new SampleSpec { BodyText = "body" });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.PowerPointLegacy);

            Assert.False(((PowerPointFormatMetadata)result.FormatMetadata!).HasMacros);
            Assert.Empty(result.EmbeddedFiles);
        }

        [Fact]
        public void RoundTrip_EmptyBody_ProducesReadableFileWithEmptyText()
        {
            var sample = new PptSampleGenerator().Generate(new SampleSpec());

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.PowerPointLegacy);

            Assert.Equal(string.Empty, result.ExtractedText);
        }
    }
}
