using ExtractorOLE.DTOs;
using ExtractorOLE.Helpers;
using SampleGenerator.Abstractions;
using SampleGenerator.Fixtures;
using SampleGenerator.Generators;
using Xunit;

namespace ExtractorOLE.Tests.SampleGeneration
{
    // T-b856b14e: XlsSampleGenerator authors a real legacy .xls via NPOI HSSFWorkbook. Every test
    // reads the generated bytes back through ExtractorOLE's public Extract path (XlsOpenStrategy +
    // XlsTextExtractor), never through the generator.
    public class XlsSampleGeneratorTests
    {
        private static readonly string[] Lines =
        {
            MultilingualFixtures.Hebrew,
            MultilingualFixtures.Arabic,
            MultilingualFixtures.Persian,
            MultilingualFixtures.Russian,
            MultilingualFixtures.Latin,
            MultilingualFixtures.Cjk,
            MultilingualFixtures.EmojiSimple,
            MultilingualFixtures.EmojiFamilyZwj,
            MultilingualFixtures.EmojiSkinTone,
            MultilingualFixtures.EmojiFlagZwj,
            "café café",
        };

        [Fact]
        public void Generate_DoesNotThrowAndProducesCfbDetectedAsExcelLegacy()
        {
            var sample = new XlsSampleGenerator().Generate(new SampleSpec { BodyText = "hello" });

            Assert.Equal("sample.xls", sample.FileName);
            Assert.Equal(OfficeMimeTypeEnum.ExcelLegacy,
                new ExtractionHelper().DetectMimeTypeFromBytes(sample.Content));
        }

        [Fact]
        public void RoundTrip_MultilingualAndEmojiBody_ReadsBackExactly()
        {
            var sample = new XlsSampleGenerator().Generate(new SampleSpec
            {
                BodyText = string.Join(Environment.NewLine, Lines),
            });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.ExcelLegacy);

            Assert.Equal(string.Join(Environment.NewLine, Lines), result.ExtractedText);
        }

        [Theory]
        [InlineData(0)]
        [InlineData(1)]
        [InlineData(2)]
        [InlineData(3)]
        [InlineData(4)]
        [InlineData(5)]
        [InlineData(6)]
        [InlineData(7)]
        [InlineData(8)]
        [InlineData(9)]
        [InlineData(10)]
        public void RoundTrip_EachFixtureRoundTripsWithExactStringEquality(int index)
        {
            var sample = new XlsSampleGenerator().Generate(new SampleSpec { BodyText = Lines[index] });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.ExcelLegacy);

            Assert.Equal(Lines[index], result.ExtractedText);
        }

        [Fact]
        public void RoundTrip_MetadataEmbeddingsAndMacros_ReadBackThroughXlsOpenStrategy()
        {
            var sample = new XlsSampleGenerator().Generate(new SampleSpec
            {
                BodyText = "body",
                Metadata = new Dictionary<string, string>
                {
                    [MetadataFields.Title] = MultilingualFixtures.Hebrew,
                    [MetadataFields.Author] = MultilingualFixtures.Arabic,
                    [MetadataFields.LastModifiedBy] = MultilingualFixtures.Cjk,
                    [MetadataFields.Created] = "2026-02-03T00:00:00Z",
                    [MetadataFields.Modified] = "2026-03-19T00:00:00Z",
                },
                Embeddings =
                {
                    new EmbeddedContentSpec { FileName = "pic.png", ContentType = "image/png", Content = new byte[] { 9, 8, 7 } },
                    new EmbeddedContentSpec { FileName = "a.bin", Content = new byte[] { 1, 2, 3 } },
                    new EmbeddedContentSpec { FileName = "b.bin", Content = new byte[] { 4, 5, 6, 7 } },
                },
                VbaProject = new byte[] { 0xAA, 0xBB },
            });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.ExcelLegacy);

            Assert.Equal(MultilingualFixtures.Hebrew, result.Metadata.Title);
            Assert.Equal(MultilingualFixtures.Arabic, result.Metadata.Creator);
            Assert.Equal(MultilingualFixtures.Cjk, result.Metadata.LastModifiedBy);
            Assert.Equal(new DateTime(2026, 2, 3, 0, 0, 0, DateTimeKind.Utc), result.Metadata.Created!.Value.ToUniversalTime());
            Assert.Equal(new DateTime(2026, 3, 19, 0, 0, 0, DateTimeKind.Utc), result.Metadata.Modified!.Value.ToUniversalTime());
            // 2 OLE objects + the user picture + the shared icon picture the OLE objects need.
            Assert.Equal(4, result.EmbeddedFiles.Count);
            Assert.True(((ExcelFormatMetadata)result.FormatMetadata!).HasMacros);
        }

        [Fact]
        public void RoundTrip_NoMacroSpec_HasMacrosFalse()
        {
            var sample = new XlsSampleGenerator().Generate(new SampleSpec { BodyText = "body" });

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.ExcelLegacy);

            Assert.False(((ExcelFormatMetadata)result.FormatMetadata!).HasMacros);
        }

        [Fact]
        public void RoundTrip_EmptyBody_ProducesReadableFileWithEmptyText()
        {
            var sample = new XlsSampleGenerator().Generate(new SampleSpec());

            var result = DocSampleGeneratorTests.Extract(sample.Content, OfficeMimeTypeEnum.ExcelLegacy);

            Assert.Equal(string.Empty, result.ExtractedText);
        }
    }
}
