using System.Collections.Concurrent;
using System.Diagnostics;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using ExtractorOLE;
using Microsoft.Extensions.DependencyInjection;

namespace ExtractorOLE.StressHarness
{
    /// <summary>
    /// Hand-rolled concurrent-load console harness (ADR-002).
    ///
    /// Not a unit test: exercises <see cref="MainExtractor"/> under N concurrent
    /// callers via Parallel.ForEachAsync with SemaphoreSlim-bounded concurrency,
    /// timing each call with Stopwatch and reporting throughput/latency.
    ///
    /// Usage: dotnet run --project ExtractorOLE.StressHarness -- [concurrency] [iterations] [samplesDir]
    /// All arguments are optional.
    /// </summary>
    internal static class Program
    {
        private const int DefaultConcurrency = 8;
        private const int DefaultIterations = 200;

        private static async Task Main(string[] args)
        {
            int concurrency = args.Length > 0 && int.TryParse(args[0], out var c) ? c : DefaultConcurrency;
            int iterations = args.Length > 1 && int.TryParse(args[1], out var i) ? i : DefaultIterations;
            string? samplesDir = args.Length > 2 ? args[2] : null;

            var samples = LoadSamples(samplesDir);

            Console.WriteLine($"Samples: {samples.Count} | Concurrency: {concurrency} | Iterations: {iterations}");

            var services = new ServiceCollection();
            ServiceRegistration.Register(services);
            using var provider = services.BuildServiceProvider();
            var extractor = provider.GetRequiredService<MainExtractor>();

            var latencies = new ConcurrentBag<double>();
            long failures = 0;

            using var gate = new SemaphoreSlim(concurrency);
            var indices = Enumerable.Range(0, iterations);

            var overall = Stopwatch.StartNew();

            await Parallel.ForEachAsync(indices, async (index, ct) =>
            {
                await gate.WaitAsync(ct);
                try
                {
                    var bytes = samples[index % samples.Count];
                    var sw = Stopwatch.StartNew();
                    await Task.Run(() => extractor.Extract(bytes), ct);
                    sw.Stop();
                    latencies.Add(sw.Elapsed.TotalMilliseconds);
                }
                catch (Exception ex)
                {
                    Interlocked.Increment(ref failures);
                    Console.WriteLine($"[iteration {index}] failed: {ex.Message}");
                }
                finally
                {
                    gate.Release();
                }
            });

            overall.Stop();

            PrintSummary(overall.Elapsed, latencies.ToList(), failures, iterations);
        }

        private static List<byte[]> LoadSamples(string? samplesDir)
        {
            var samples = new List<byte[]>();

            if (!string.IsNullOrWhiteSpace(samplesDir) && Directory.Exists(samplesDir))
            {
                foreach (var file in Directory.EnumerateFiles(samplesDir))
                {
                    samples.Add(File.ReadAllBytes(file));
                }
            }

            if (samples.Count == 0)
            {
                Console.WriteLine("No sample directory provided (or it was empty) - generating a synthetic in-memory .docx sample.");
                samples.Add(CreateSyntheticDocx());
            }

            return samples;
        }

        private static byte[] CreateSyntheticDocx()
        {
            using var stream = new MemoryStream();
            using (var doc = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document))
            {
                var mainPart = doc.AddMainDocumentPart();
                mainPart.Document = new Document(
                    new Body(
                        new Paragraph(
                            new Run(
                                new Text("Synthetic load-test document generated by ExtractorOLE.StressHarness.")))));
                mainPart.Document.Save();
            }

            return stream.ToArray();
        }

        private static void PrintSummary(TimeSpan elapsed, List<double> latencies, long failures, int totalIterations)
        {
            latencies.Sort();
            var succeeded = latencies.Count;
            var throughput = elapsed.TotalSeconds > 0 ? succeeded / elapsed.TotalSeconds : 0;

            Console.WriteLine();
            Console.WriteLine("=== Stress harness summary ===");
            Console.WriteLine($"Total iterations : {totalIterations}");
            Console.WriteLine($"Succeeded        : {succeeded}");
            Console.WriteLine($"Failed           : {failures}");
            Console.WriteLine($"Wall-clock time  : {elapsed.TotalSeconds:F3} s");
            Console.WriteLine($"Throughput       : {throughput:F2} ops/sec");

            if (succeeded > 0)
            {
                Console.WriteLine($"Latency min      : {latencies[0]:F2} ms");
                Console.WriteLine($"Latency avg      : {latencies.Average():F2} ms");
                Console.WriteLine($"Latency p50      : {Percentile(latencies, 50):F2} ms");
                Console.WriteLine($"Latency p95      : {Percentile(latencies, 95):F2} ms");
                Console.WriteLine($"Latency p99      : {Percentile(latencies, 99):F2} ms");
                Console.WriteLine($"Latency max      : {latencies[^1]:F2} ms");
            }
        }

        private static double Percentile(List<double> sortedLatencies, double percentile)
        {
            if (sortedLatencies.Count == 0) return 0;

            var rank = (percentile / 100.0) * (sortedLatencies.Count - 1);
            var lower = (int)Math.Floor(rank);
            var upper = (int)Math.Ceiling(rank);
            if (lower == upper) return sortedLatencies[lower];

            var frac = rank - lower;
            return sortedLatencies[lower] + frac * (sortedLatencies[upper] - sortedLatencies[lower]);
        }
    }
}
